name: tex_to_pdf

on:
  push:
    braches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Dependencies
      run: |
          sudo apt-get update -y
          sudo apt install -y \
            texlive-latex-base \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-latex-extra \
            texlive-luatex

    - name: Compile
      run: |
        cd /home/runner/work/latex/latex/koma-script/voorbeelden/book/
        lualatex -interaction=nonstopmode scrbook-voorbeeld.tex

    - name: Commit and push PDFs
      run: |
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add koma-script/*.pdf
            git commit -m "Update generated PDFs" || echo "No changes to commit"
            git push
